### ISSUE TITLE
Firebase SDK 10.0.1でNullPointerExceptionが発生する

### ISSUE THREAD

**Issue by sakebook** [mtburn/MTBurn-Android-SDK-Install-Guide#9]
FirebaseのSDKのバージョンを9.6.1から10.0.1へ上げたところ、クラッシュが発生するようになりました。

手元の端末では確認できてないのですが、次のようなクラッシュログが上がってくるようになりました。

OSやメーカーによらず、まばらに発生しています。

こちら対応予定はありますでしょうか？ご確認よろしくお願いいたします。

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.NullPointerException
       at com.mtburn.android.sdk.AppDavis$AdvertisingIdTask.getAdvertisingId(AppDavis.java:223)
       at com.mtburn.android.sdk.AppDavis$AdvertisingIdTask.doInBackground(AppDavis.java:212)
       at com.mtburn.android.sdk.AppDavis$AdvertisingIdTask.doInBackground(AppDavis.java:1)
       at com.mtburn.android.sdk.util.BaseAsyncTask$InnerTask.doInBackground(BaseAsyncTask.java:86)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by yoheimuta** [comment]
ご報告ありがとうございます。

> こちら対応予定はありますでしょうか？

同様の事象は今まで報告されていなかったため、現在のところ対応予定はありませんでしたが、対応を検討したいと思います。

ただ、再現が難航しそうな点と報告事例がまだほかにないことから、目下の対応優先度は中くらいという位置づけで進めさせていただくことになると思います。

お手数ですが、よろしくお願いします。

**Comment by katohiromasa** [comment]
こちらでも同様のバグでのクラッシュが90件以上上がっています。

**Comment by yoheimuta** [comment]
@sakebook @katohiromasa https://github.com/mtburn/MTBurn-Android-SDK-Install-Guide/releases/tag/v1.2.2 で AppDavis$AdvertisingIdTask.getAdvertisingId の NullPointerException を catch するように修正しました。

google-play-services のアップデートタイミングでまばらに発生することがほかの利用アプリからも報告されています。

お手数ですが、ご確認ください。

**Comment by yoheimuta** [comment]
クローズします。再発するようであれば、リオープンください。
